# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  encoding: utf8
  database: etracker_dev
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock
  reconnect: true

test:
  adapter: mysql2
  encoding: utf8
  database: etracker_testing
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock
  reconnect: true

production:
  adapter: mysql2
  encoding: utf8
  database: etracker
  username: etracker
  password: TaLgx694nL3EKL0IGB3vsMUZ